Ssahu06
ActianCorp/actian_tableau_connector pull request #4
Opened 2020-01-21 10:04 UTC by ssahu06

2020-01-21 10:04 UTC, ssahu06 commented
Adding REPEAT in place of LEFT

2020-01-21 21:57 UTC, clach04 requested changes
A couple of the commit messages have what look like vim directives and there are some changes that where made and then undone. Those need clean up

Please can you squash your commits and ensure the commit message has an a explanation on the "why". Your diff and existing comment are good "what" explanations.

If git squash sounds daunting, there are alternatives:
1. to re-branch and then make the change as a single commit. It would likely be quicker in this instance (but for more complicated changes squashing is a useful technique).
2. update the PR description/title and then I can squash when I accept - this is likely the easiest option for you and the one I recommend

2020-01-21 21:57 UTC, clach04 commented on actian_odbc/dialect.tdd
> +		<formula>(CASE WHEN %1 IS NOT NULL AND CAST(%1 AS INTEGER) &gt; 0 THEN REPEAT(&apos; &apos;,CAST(%1 AS INTEGER) ELSE NULL END)</formula>
Change looks good, the change description needs an explanation on why the change is being made. For example, "fixes SQL error by calling REPLACE() instead of LEFT().

Right now I'm not clear why the change is needed, I'm sure there is a good reason, we need to make a note about it. A sentence is fine.

2020-01-22 02:56 UTC, closed without merging

2020-01-22 18:57 UTC, clach04 commented
Handled by PR 5